window.ASMART_SERVICES = {
  categories: [
    {
      id: 'digital',
      name: 'Digital & Development',
      icon: 'fa-laptop-code',
      description: 'Websites, apps, design, SEO, and digital marketing for Uganda businesses.',
    },
    {
      id: 'business',
      name: 'Business & Online Support',
      icon: 'fa-briefcase',
      description: 'Consulting, social media, email setup, and online errands for local clients.',
    },
    {
      id: 'office',
      name: 'Office & Document Services',
      icon: 'fa-file-alt',
      description: 'Typing, data entry, printing, training, and everyday office tasks.',
    },
    {
      id: 'tech-support',
      name: 'Tech Support & Installation',
      icon: 'fa-tools',
      description: 'Repairs, CCTV, WiFi, software, and data recovery — on-site and remote across all Uganda.',
    },
  ],
  items: [
    {
      id: 'supermarket-software',
      category: 'digital',
      name: 'SuperMKT — Supermarket Management System',
      icon: 'fa-shopping-cart',
      description: 'Uganda\'s supermarket POS, inventory, MoMo/Airtel payments, VAT tracking & live sales dashboards. From UGX 80K/month.',
      features: ['POS & inventory', 'MTN MoMo & Airtel Money', '18% VAT tracking', 'Offline-ready', 'Live sales dashboard'],
      slug: 'supermarket-software-uganda',
      keywords: ['supermarket software Uganda', 'POS system Uganda', 'SuperMKT'],
      links: {
        app: 'https://supermkt-n1nf.onrender.com/login',
        sales: 'https://sales-i9to.onrender.com',
      },
    },
    {
      id: 'web-design',
      category: 'digital',
      name: 'Web Design & Development',
      icon: 'fa-globe',
      description: 'Beautiful, fast, SEO-optimized websites for shops, schools, clinics, churches, and startups.',
      features: ['Responsive design', 'SEO setup', 'WhatsApp integration', 'Fast hosting'],
      slug: 'web-designer-uganda',
      keywords: ['web designer Uganda', 'website design Kagadi'],
    },
    {
      id: 'website-design',
      category: 'digital',
      name: 'Website Design',
      icon: 'fa-store',
      description: 'Simple professional websites for shops, schools, churches, and small businesses.',
      features: ['Multi-page sites', 'Contact forms', 'Google Maps', 'Mobile-friendly'],
      slug: 'web-designer-uganda',
      keywords: ['website design Uganda', 'cheap website Kagadi'],
    },
    {
      id: 'mobile-apps',
      category: 'digital',
      name: 'Mobile App Development',
      icon: 'fa-mobile-alt',
      description: 'Android apps with React Native and Expo for business, education, ecommerce, and media.',
      features: ['React Native', 'Play Store publishing', 'API integration', 'Firebase backend'],
      slug: 'app-developer-uganda',
      keywords: ['app developer Uganda', 'Android developer Kagadi'],
    },
    {
      id: 'ui-ux',
      category: 'digital',
      name: 'UI/UX Design',
      icon: 'fa-paint-brush',
      description: 'User-centered designs that are beautiful, intuitive, and engaging.',
      features: ['Wireframing', 'Prototyping', 'Figma designs', 'User research'],
      slug: 'graphic-design-uganda',
      keywords: ['UI design Uganda', 'UX designer Kagadi'],
    },
    {
      id: 'seo',
      category: 'digital',
      name: 'SEO Optimization',
      icon: 'fa-search',
      description: 'Rank on Google for local searches in Kampala, Kagadi, and across Uganda.',
      features: ['Keyword research', 'On-page SEO', 'Search Console', 'Content strategy'],
      slug: 'seo-small-business-uganda',
      keywords: ['SEO Uganda', 'Google ranking Kagadi'],
    },
    {
      id: 'app-publishing',
      category: 'digital',
      name: 'App Publishing',
      icon: 'fa-rocket',
      description: 'Complete app store submission to Google Play, Amazon, and APKPure.',
      features: ['Store optimization', 'Submission process', 'Updates & maintenance'],
      slug: 'app-developer-uganda',
      keywords: ['app publishing Uganda'],
    },
    {
      id: 'digital-consulting',
      category: 'digital',
      name: 'Digital Consulting',
      icon: 'fa-chart-line',
      description: 'Expert advice on digital strategy, technology stack, and growth for African businesses.',
      features: ['Strategy planning', 'Tech stack advice', 'Growth hacking'],
      slug: 'tech-consulting-uganda',
      keywords: ['digital consulting Uganda'],
    },
    {
      id: 'performance-marketing',
      category: 'digital',
      name: 'Performance Marketing',
      icon: 'fa-bullhorn',
      description: 'Google Ads and YouTube Ads campaigns designed for conversion and growth.',
      features: ['Google Search & Display', 'YouTube Ads', 'Landing page optimization'],
      slug: 'seo-small-business-uganda',
      keywords: ['Google Ads Uganda', 'YouTube Ads Kagadi'],
    },
    {
      id: 'graphic-design',
      category: 'digital',
      name: 'Graphic Design',
      icon: 'fa-palette',
      description: 'Logos, flyers, posters, and social media graphics using Canva or Adobe.',
      features: ['Logo design', 'Flyers & posters', 'Social media kits', 'Brand identity'],
      slug: 'graphic-design-uganda',
      keywords: ['graphic design Uganda', 'logo design Kagadi'],
    },
    {
      id: 'photo-editing',
      category: 'digital',
      name: 'Photo Editing',
      icon: 'fa-camera',
      description: 'Edit passport photos, event photos, and product images for print or web.',
      features: ['Passport photos', 'Background removal', 'Event editing', 'Print-ready exports'],
      slug: 'graphic-design-uganda',
      keywords: ['photo editing Uganda', 'passport photo Kagadi'],
    },
    {
      id: 'tech-consulting',
      category: 'business',
      name: 'Tech Consulting',
      icon: 'fa-user-cog',
      description: 'Help individuals and businesses choose the right devices, software, and internet plans.',
      features: ['Device recommendations', 'Software selection', 'Internet plan advice', 'Per session or hourly'],
      slug: 'tech-consulting-uganda',
      keywords: ['tech consulting Uganda', 'IT advice Kagadi'],
    },
    {
      id: 'social-media',
      category: 'business',
      name: 'Social Media Management',
      icon: 'fa-hashtag',
      description: 'Run Facebook, Instagram, and TikTok pages for local businesses.',
      features: ['Content posting', 'Page setup', 'Engagement replies', 'Monthly retainer'],
      slug: 'social-media-management-uganda',
      keywords: ['social media management Uganda', 'Facebook page manager Kagadi'],
    },
    {
      id: 'email-setup',
      category: 'business',
      name: 'Email & Business Setup',
      icon: 'fa-envelope-open-text',
      description: 'Set up Gmail, WhatsApp Business, and Google accounts for clients.',
      features: ['Gmail setup', 'WhatsApp Business', 'Google Business Profile', 'Account recovery help'],
      slug: 'tech-consulting-uganda',
      keywords: ['email setup Uganda', 'WhatsApp Business Kagadi'],
    },
    {
      id: 'online-errands',
      category: 'business',
      name: 'Online Errands',
      icon: 'fa-running',
      description: 'Pay bills, register accounts, and fill forms for non-tech clients.',
      features: ['Bill payments', 'Account registration', 'Form filling', 'Online submissions'],
      slug: 'tech-consulting-uganda',
      keywords: ['online errands Uganda', 'digital assistant Kagadi'],
    },
    {
      id: 'cv-typing',
      category: 'office',
      name: 'CV & Document Typing',
      icon: 'fa-keyboard',
      description: 'Type CVs, letters, application forms, and official documents professionally.',
      features: ['Professional CVs', 'Cover letters', 'Application forms', 'Formatting & printing'],
      slug: 'cv-typing-services-uganda',
      keywords: ['CV typing Uganda', 'document typing Kagadi'],
    },
    {
      id: 'data-entry',
      category: 'office',
      name: 'Data Entry',
      icon: 'fa-table',
      description: 'Enter data for businesses or online clients — accurate and confidential.',
      features: ['Spreadsheets', 'Database entry', 'Form digitization', 'Per hour or per task'],
      slug: 'cv-typing-services-uganda',
      keywords: ['data entry Uganda', 'typing services Kagadi'],
    },
    {
      id: 'printing',
      category: 'office',
      name: 'Printing & Photocopying',
      icon: 'fa-print',
      description: 'Print documents, IDs, forms, and photos for walk-in and remote clients.',
      features: ['Document printing', 'Photocopying', 'ID photos', 'Binding & lamination'],
      slug: 'printing-services-uganda',
      keywords: ['printing services Uganda', 'photocopy Uganda', 'print shop Kampala'],
    },
    {
      id: 'training',
      category: 'office',
      name: 'Training & Lessons',
      icon: 'fa-chalkboard-teacher',
      description: 'Teach computer basics, MS Office, internet use, and smartphone skills.',
      features: ['Computer basics', 'MS Word & Excel', 'Internet & email', 'One-on-one sessions'],
      slug: 'tech-consulting-uganda',
      keywords: ['computer training Uganda', 'MS Office lessons Kagadi'],
    },
    {
      id: 'cctv',
      category: 'tech-support',
      name: 'CCTV & Security Camera Installation',
      icon: 'fa-video',
      description: 'Install home and office security cameras with remote viewing setup.',
      features: ['Camera installation', 'DVR/NVR setup', 'Mobile app viewing', 'Maintenance'],
      slug: 'cctv-installation-uganda',
      keywords: ['CCTV installation Uganda', 'security cameras Kagadi'],
    },
    {
      id: 'phone-repair',
      category: 'tech-support',
      name: 'Mobile Phone Repair',
      icon: 'fa-mobile',
      description: 'Screen replacements, battery swaps, and software flashing for Android phones.',
      features: ['Screen repair', 'Software flashing', 'Battery replacement', 'Data backup'],
      slug: 'computer-phone-repair-uganda',
      keywords: ['phone repair Uganda', 'computer repair Uganda', 'mobile repair Kampala'],
    },
    {
      id: 'networking',
      category: 'tech-support',
      name: 'Networking & WiFi Setup',
      icon: 'fa-wifi',
      description: 'Set up routers, extenders, and small office networks for reliable connectivity.',
      features: ['Router configuration', 'WiFi extenders', 'Office networks', 'Troubleshooting'],
      slug: 'wifi-setup-uganda',
      keywords: ['WiFi setup Uganda', 'network installation Kagadi'],
    },
    {
      id: 'software-install',
      category: 'tech-support',
      name: 'Software Installation',
      icon: 'fa-download',
      description: 'Install Windows, antivirus, MS Office, and essential software on laptops and PCs.',
      features: ['Windows installation', 'Antivirus setup', 'MS Office', 'Driver updates'],
      slug: 'software-installation-uganda',
      keywords: ['software installation Uganda', 'Windows install Kagadi'],
    },
    {
      id: 'data-recovery',
      category: 'tech-support',
      name: 'Data Recovery',
      icon: 'fa-hdd',
      description: 'Recover lost files from phones, laptops, USB drives, and memory cards.',
      features: ['Phone recovery', 'Hard drive recovery', 'Formatted drives', 'Corrupted files'],
      slug: 'data-recovery-uganda',
      keywords: ['data recovery Uganda', 'file recovery Kagadi'],
    },
  ],
  searchGuides: [
    {
      title: 'Supermarket Software Uganda',
      slug: 'supermarket-software-uganda',
      description: 'SuperMKT — POS, inventory, MoMo payments & sales tracking for Ugandan supermarkets.',
      icon: 'fa-shopping-cart',
    },
    {
      title: 'Web Designer in Uganda',
      slug: 'web-designer-uganda',
      description: 'Professional websites for schools, clinics, restaurants, shops, and startups.',
      icon: 'fa-globe',
    },
    {
      title: 'App Developer in Uganda',
      slug: 'app-developer-uganda',
      description: 'Android apps for business, ecommerce, education, and media.',
      icon: 'fa-mobile-alt',
    },
    {
      title: 'Tech Consulting in Uganda',
      slug: 'tech-consulting-uganda',
      description: 'Choose the right devices, software, and internet plans for your needs.',
      icon: 'fa-user-cog',
    },
    {
      title: 'Printing Services Uganda',
      slug: 'printing-services-uganda',
      description: 'Printing, photocopying, IDs and document services nationwide.',
      icon: 'fa-print',
    },
    {
      title: 'Phone & Computer Repair Uganda',
      slug: 'computer-phone-repair-uganda',
      description: 'Screen repair, software flashing, and hardware fixes nationwide.',
      icon: 'fa-tools',
    },
    {
      title: 'CCTV Installation Uganda',
      slug: 'cctv-installation-uganda',
      description: 'Home and office security cameras with remote viewing.',
      icon: 'fa-video',
    },
    {
      title: 'WiFi & Network Setup Uganda',
      slug: 'wifi-setup-uganda',
      description: 'Router setup, office networks, and reliable internet for businesses.',
      icon: 'fa-wifi',
    },
    {
      title: 'CV & Document Typing Uganda',
      slug: 'cv-typing-services-uganda',
      description: 'Professional CVs, letters, and form typing for job seekers.',
      icon: 'fa-keyboard',
    },
    {
      title: 'Graphic Design Uganda',
      slug: 'graphic-design-uganda',
      description: 'Logos, flyers, posters, and social media graphics.',
      icon: 'fa-palette',
    },
    {
      title: 'Social Media Management Uganda',
      slug: 'social-media-management-uganda',
      description: 'Facebook, Instagram, and TikTok management for local businesses.',
      icon: 'fa-hashtag',
    },
    {
      title: 'SEO for Small Business Uganda',
      slug: 'seo-small-business-uganda',
      description: 'Rank on Google in Kampala, upcountry towns, and across Uganda.',
      icon: 'fa-search',
    },
    {
      title: 'School Website Uganda',
      slug: 'school-website-uganda',
      description: 'Websites for schools with admissions, fees info, and parent communication.',
      icon: 'fa-school',
    },
    {
      title: 'Clinic Website Uganda',
      slug: 'clinic-website-uganda',
      description: 'Help patients find your clinic, services, and contacts on Google.',
      icon: 'fa-hospital',
    },
    {
      title: 'SACCO Digital Services Uganda',
      slug: 'sacco-digital-services-uganda',
      description: 'Digital trust pages and member inquiry workflows for SACCOs.',
      icon: 'fa-university',
    },
    {
      title: 'Software Installation Uganda',
      slug: 'software-installation-uganda',
      description: 'Windows, antivirus, MS Office, and essential software setup.',
      icon: 'fa-download',
    },
    {
      title: 'Data Recovery Uganda',
      slug: 'data-recovery-uganda',
      description: 'Recover lost files from phones, laptops, and storage devices.',
      icon: 'fa-hdd',
    },
    {
      title: 'Website Cost in Uganda',
      slug: 'website-cost-uganda',
      description: 'Understand what affects website pricing — every project quoted on negotiation.',
      icon: 'fa-handshake',
    },
  ],
};
